name: CD Dev

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  PR-CD-Dev:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'mknet-dev'
      uniquelabel: 'mknetdev'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_MKNETDEV }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}