on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - dev
    
name: Azure CD
jobs:
  Deploy-Infrastrcuture:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: BicepDeploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./bicep/main.bicep
        failOnStdErr: false        

    - name: BicepOutputFunctionName
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g mknet-dev --name main --query properties.outputs.functionAppName.value -o tsv)
          echo "FunctionName=$outputValue" >> $GITHUB_ENV
     
    - name: DotnetBuildWorkflow
      shell: bash
      run: |
        pushd './src/Workflow'
        dotnet build --configuration Release --output ./output
        popd
          
    - name: DeployWorkflow
      uses: Azure/functions-action@v1.4.8
      with:
        app-name: ${{ env.FunctionName }}
        package: './src/Workflow/output'

    - name: BicepOutputWebName
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g mknet-dev --name main --query properties.outputs.webAppName.value -o tsv)
          echo "WebAppName=$outputValue" >> $GITHUB_ENV   

    - name: DotnetBuildWeb
      shell: bash
      run: |
        pushd './src/Web'
        dotnet build --configuration Release --output ./output
        popd
          
    - name: DeployWeb
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebAppName }}
        package: './src/Web/output'
