name: CD Dev

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  CD-Dev:
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'MartinkMeDev'
      unique-label: 'foo'
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      github-pat: ${{ secrets.GH_PAT }}