name: CD Dev

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  PR-CD-Dev:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/deployment.yml
    with:
      rg: 'mknet-dev'
      uniquelabel: 'mknetdev'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}