on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - dev
    
name: Azure CD
jobs:
  Deploy-Infrastructure:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: BicepDeploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./bicep/main.bicep
        failOnStdErr: false        

# Web App
    - name: bicep-output-webappname
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g mknet-dev --name main --query properties.outputs.webAppName.value -o tsv)
          echo "WebAppName=$outputValue" >> $GITHUB_ENV   

    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: dotnet-build-publish-webapp
      run: |
        dotnet restore ./src/Web/Web.csproj
        dotnet build ./src/Web/Web.csproj --configuration Release
        dotnet publish ./src/Web/Web.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

    - name: azure-deploy-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WebAppName }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

# Function
    - name: BicepOutputFunctionName
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g mknet-dev --name main --query properties.outputs.functionAppName.value -o tsv)
          echo "FunctionName=$outputValue" >> $GITHUB_ENV
     
    - name: DotnetBuildWorkflow
      shell: bash
      run: |
        pushd './src/Workflow'
        dotnet build --configuration Release --output ./output
        popd
          
    - name: DeployWorkflow
      uses: Azure/functions-action@v1.4.8
      with:
        app-name: ${{ env.FunctionName }}
        package: './src/Workflow/output'
