on: [push]
name: Azure CD
jobs:
  Deploy-Infrastrcuture:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: Checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # Get outputs
    - name: BicepOutput
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          outputValue=$( az deployment group show -g mknet-dev --name main --query properties.outputs.functionAppName.value | tr -d '"')
          echo "FunctionAppName=outputValue" >> $GITHUB_ENV
          
    - name: Display
      run: echo 'Function app name ${{ env.FunctionAppName }}'
     
      # Dotnet build
    - name: DotnetBuild
      shell: bash
      run: |
        pushd './src/Workflow'
        dotnet build --configuration Release --output ./output
        popd
          
      # Deploy Function
    - name: DeployFunction
      uses: Azure/functions-action@v1.4.8
      with:
        app-name: $(FunctionAppName)
        package: './src/Workflow/output'
        
      # Deploy Bicep file
    - name: BicepDeploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./src/Bicep/main.bicep
        failOnStdErr: false
      
