name: Obtain Subscription Id

on:
  workflow_dispatch:
  push:

jobs:
  ObtainId:
    name: Obtain Subscription Id
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: |
           echo $SUBSCRIPTION | awk '{print substr($0,1,18)}'
           echo $SUBSCRIPTION | awk '{print substr($0,19,18)}'
      - shell: bash
        env:
          CREDS: ${{ secrets.AZURE_CREDENTIALS_MKNETPROD }}
        run: |
           echo $CREDS | awk '{print substr($0,1,18)}'
           echo $CREDS | awk '{print substr($0,19,18)}'
          
