name: Pulumi Up on Push
on:
  push:
    branches:
      - 2021Rewrite
jobs:
  preview:
    name: Build Publish and Deploy
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .net 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: Setup .net 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
          
      - name: .net Restore
        run: dotnet restore

      - name: .net Build
        run: dotnet build --no-restore --configuration Release
          
      - name: .net Publish MartinKMe.Functions  
        run: dotnet publish --no-restore --configuration Release --output MartinKMe.Infrastructure/publishfunctions MartinKMe.Functions/MartinKMe.Functions.csproj
          
      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: MartinKMe.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
           
      - name: Print all env vars
        run: env

      - name: .net Test
        run: dotnet test --no-restore
        env:
          Settings:GithubPat: ${{ secrets.SETTINGS_GITHUBPAT }}
          
